### ISSUE TITLE
参数名称词库

### ISSUE THREAD

**Issue by huntbao** [x-orpheus/nei-toolkit#109]
接口的字段名称，维护一个字段库，填写的字段必须来自这个库，否则就无法保存成功

**Comment by huntbao** [comment]
具体需求及实现如下：
- 增加一种资源类型，如“参数词库”。
- 系统有预置的词库，比如最常见的 `id`、`name`、`code`等。
- 项目组可以维护词库，项目组中的所有项目可以使用。
- 项目可以有自己的词库。
> 优先级为 项目 > 项目组 > 系统预置
- 项目组和项目中的词可以设置为禁用，比如可以禁止使用 `name` 这个参数名称。
- 支持联想功能，比如用户输入 `acountName`时，系统需要提示应该为 `accountName`。联想列表支持用户在创建词的时候输入，也可以自动从现有词库中查找。参考  [Levenshtein Distance](https://en.wikipedia.org/wiki/Levenshtein_distance)是否符合需求，性能是否有问题等。
- 在创建词的时候，如果系统中已经存在，则需要提示用户。
- 有编辑权限的用户都能对词库进行操作。

**Comment by kkdev163** [comment]
联想功能已按  Levenshtein Distance 算法实现了[Demo](https://codepen.io/kkdev163/pen/ZEEmOda)，当我们词库量在几千以内时，几乎是1毫秒内能匹配出的。
