### ISSUE TITLE
NEI导出功能咨询

### ISSUE THREAD

**Issue by wenhao0514** [x-orpheus/nei-toolkit#118]
目前NEI控制台不支持导出功能，看与其他人沟通需要通过NEI toolkit导出，安装好NEI toolkit后看帮助没有找到导出帮助，请问导出功能是否有说明文档或示例？

**Comment by huntbao** [comment]
工程规范可以导出的：https://github.com/x-orpheus/nei-toolkit#NEI-工程规范介绍

文件模板需要自己写，传给模板的数据见上述文档的说明。一个生成 javabean 的示例：https://github.com/x-orpheus/nei-toolkit/blob/master/doc/一步一步教你如何愉快地生成JavaBean文件.md
